WebAppDB/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppDB.Data;
using WebAppDB.Models;

namespace WebAppDB.Controllers
{
    public class LanguageController : Controller
    {
        //Create Interface object
        readonly ILanguageRepo _languageService;
        //DI context
        private readonly MyDbContext _context;

        //DI interface
        public LanguageController(ILanguageRepo languageService, MyDbContext context)
        {
            _languageService = languageService;

            //DI context
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_languageService.Read());
        }

        [HttpGet]//View Form page
        public IActionResult Create()
        {
            //City city = new City();
            // return View(city);
            return View();
        }
        [HttpPost]//Send Data to server via form
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind(" LanguageID, LanguageName")] Language city)
        {
            if (ModelState.IsValid)
            {
                //_context.Add(student);
                // await _context.SaveChangesAsync();
                _languageService.Create(city);
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        //Edit
        public IActionResult Edit(int id)

        {
            if (id == 0)
            {
                return NotFound();
            }

            var city = _languageService.Read(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);

        }

        [HttpPost]//Send Data to server via form
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind(" LanguageID, LanguageName")] Language city)//ID should be same in Entity
        {
            if (id != city.LanguageID)//
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //_context.Add(student);
                // await _context.SaveChangesAsync();
                // _cityService.Create(city);
                _languageService.Update(city);
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        //Delete get
        public IActionResult Delete(int id)

        {
            if (id == 0)
            {
                return NotFound();
            }

            var city = _languageService.Read(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);

        }


        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var city = _languageService.Read(id);
            _languageService.Delete(city);
            return RedirectToAction(nameof(Index));
        }

        //Language person extra

        public IActionResult Index2(int id)
        {
            var person= _context.Pepoles
                                   .Where(s => s.Id == id)
                                      .ToList();
            foreach (Person  per in person)
            {
                ViewBag.Msg = per.FirstName+" "+per.LastName;
            }
            return View(_languageService.Read());
        }

        public IActionResult Add(int id)
        {
           
            //
            var perso = _context.Languages
                                  .Where(s => s.LanguageID == id)
                                     .ToList();
            foreach (Language per in perso)
            {
                ViewBag.Languge = per.LanguageName;
            }
            //
            var city = _languageService.Read(id);
            _languageService.Delete(city);
            return RedirectToAction(nameof(Index2));
        }

        public IActionResult Edit2(int id)
        {
            //ViewBag.Msg = "Hellow Esam";
             //
             /*
             var perso = _context.Languages
                                  .Where(s => s.LanguageID == id)
                                     .ToList();

            if (perso != null) { ViewBag.Msg = "List Languge is not empty"; }

          


            foreach (Language per in perso)
            {
                ViewBag.Languge = per.LanguageName;
            }*/
           
            return View(_languageService.Read());
        }


        }//End class



}

WebAppDB/Controllers/PeoplesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppDB.Data;
using WebAppDB.Models;

namespace WebAppDB.Controllers
{
   
    public class PeoplesController : Controller
    {
        
        //Create Interface object
      readonly  IPeopleService peopleService;//Used also in part#4 &5
        //Create Interface object for person
        readonly IPeopleRepo personService;//Part#4, this is will make change context throgh
                                           //DatabasePepleRepo , this Interface will invoke all InMemoryPeopleRepo methds

        //DI contxt part#/

        private readonly MyDbContext _context;
        public PeoplesController(IPeopleService peopleService2, IPeopleRepo personService2, MyDbContext context)
        {
            peopleService = new PeopleService();//Is that correct?
            //
           // personService = new InMemoryPeopleRepo();//Do not used yet!
               
            peopleService= peopleService2; //Is it work?What is benfit?

            //Part#5

            personService = personService2;

            //Part#7
            _context = context;
        }
        /*Part#7*/

       
        public IActionResult Index2()
        {
            // return View(peopleService.All());
            return View(personService.Read());

        }
       
        [HttpGet]//View Form page
        public IActionResult Create2()
        {
            //City city = new City();
            // return View(city);
            return View();
        }
       
        [HttpPost]//Send Data to server via form
        [ValidateAntiForgeryToken]
        public IActionResult Create2([Bind(" Id,FirstName, LastName,PhoneNumber,CityName ,CityID")] Person per)
        {
            //
            var contryget = _context.Cities.
                            Where(s => s.CityName == per.CityName)
                            .ToList();

           
                foreach (City city in contryget)
                {
                if (city.CountryName != null)
                {
                    per.CountryName = city.CountryName;
                    
                }
                else
                {
                    ViewBag.Msg = "The City is not availbel i Db , Add City & Country , then Create a person ";
                    return RedirectToAction(nameof(Index2));
                }
                }
               
                  


           if (ModelState.IsValid)
            {
               
                personService.Create(per);
                ViewBag.Msg = "Successfully add Person";
                return RedirectToAction(nameof(Index2));
            }
            return View(per);
        }


        //Edit
       
        public IActionResult Edit2(int id)

        {
            if (id == 0)
            {
                return NotFound();
            }

            var city = personService.Read(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);

        }
       
        [HttpPost]//Send Data to server via form
        [ValidateAntiForgeryToken]
        public IActionResult Edit2(int id, [Bind(" Id,FirstName, LastName,PhoneNumber,CityName ,CityID")] Person per)//ID should be same in Entity
        {
            if (id !=per.Id)//
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //_context.Add(student);
                // await _context.SaveChangesAsync();
                // _cityService.Create(city);
                personService.Update(per);
                return RedirectToAction(nameof(Index2));
            }
            return View(per);
        }

        //Delete get
        public IActionResult Delete2(int id)

        {
            if (id == 0)
            {
                return NotFound();
            }

            var city = personService.Read(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);

        }


        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete2")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var city = personService.Read(id);
            personService.Delete(city);
            return RedirectToAction(nameof(Index2));
        }

        // GET: Students/Details/5
        public IActionResult Details2(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var city = personService.Read(id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }


        /*Part#1,2,3,4,5,6****************************************************************************/
        public IActionResult Index()
        {
            // return View(peopleService.All());
            return View(personService.Read());
            
        }

        //create

        [HttpGet]//Action for page <Form> which it is Create page
        public IActionResult Create()
        {
            CreatePersonViewModel create = new CreatePersonViewModel();
            return View(create);
        }

        [HttpPost]//Action for <Form> to send information

        public IActionResult Create(
            [Bind("Id,LastName,FirstName,PhoneNumber,CityName")] Person person)
        {
            if (ModelState.IsValid)//if input data to form ok 
            {
               // peopleService.PersonAdd(create);
                personService.Create(person);
                return RedirectToAction("Index");//return to DataBase page
            }



            return View(person);

        }

        //DetailsOne
        [HttpGet] //<form> view
        public IActionResult DetailsOne(string Id)//search methd should be same like this!return view model
        {
            int result = Int32.Parse(Id);

            return View(peopleService.FindById(result));
        }

        [HttpPost, ActionName("DetailsOne")]//get id from <Form> to server
        [ValidateAntiForgeryToken]
        public IActionResult DetailsPost(int Id)//search methd should be same like this!return view model
        {
           // int result = Int32.Parse(Id);

            return View(personService.Read(Id));
            //return View(peopleService.FindById(@per.Id));
        }


        //DeleteOne <Form> View page
        [HttpGet]
        public IActionResult DeleteOne(string Id)//index file
        {

            int result = Int32.Parse(Id);
            Person delete = peopleService.FindById(result);

            //
            if (ModelState.IsValid)//if input data to form ok 
            {
                if (peopleService.Delete(delete))
                {
                    ViewBag.Inform = "Successfully Person delted this person";
                }
                return RedirectToAction("Index");//return to DataBase page
            }
            return View(null);
        }//End DeleteOne action
        /*
        [HttpPost]//Action for <Form> to send information

        public IActionResult DeleteOne(Person create)
        {
            if (ModelState.IsValid)//if input data to form ok 
            {
               // peopleService.PersonAdd(create);
                return RedirectToAction("Index");//return to DataBase page
            }



            return View(create);

        }*/

        [HttpPost, ActionName("DeleteOne")]//Just use this
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost( 
                                           [Bind("Id,LastName,FirstName,PhoneNumber,CityName")] Person person)//index file
        {                  

           
            if (ModelState.IsValid)//if input data to form ok 
            {
                if (personService.Delete(person))
                {
                    ViewBag.Inform = "Successfully Person delted this person";
                }
                return RedirectToAction("Index");//return to DataBase page
            }
            return View(person);
        }//End DeleteOne action

        //Ajax

        public IActionResult Ajax()//For Ajax page
        {
            return View();
        }

        //
        public IActionResult GetPeople()
        {
            return PartialView("_ViewPeople", personService.Read());//updated part#5
        }


        [HttpPost]
        public IActionResult Details(int find)
        {
            //int result = Int32.Parse(find);


            return PartialView("_ViewPerson", personService.Read(find));
        }

        //Delete person

        [HttpPost]

        public IActionResult DeletePerson(int Id, [Bind("Id,LastName,FirstName,PhoneNumber,CityName")] 
                                                                 Person person)//index file
        {

            //int result = Int32.Parse(Id);
            Person delete = peopleService.FindById(Id);
            //ViewBag.Inform = "hellow I am here ";
            //
            if (ModelState.IsValid)//if input data to form ok 
            {
                if (personService.Delete(person))
                {
                    ViewBag.Inform = "The person with Id= " + Id + " is successfully  delted ";//_ViewPeople

                    // return RedirectToAction("DataBase");
                    //return View();//return _ViewPeople instead!

                    return PartialView("_ViewMsg");
                }
                //return RedirectToAction("DataBase");//return to DataBase page

                else
                {
                    ViewBag.Inform = "The Person is not  delted ";
                    return PartialView("_ViewPeople");
                    // return RedirectToAction("Main");
                }

WebAppDB/Views/Peoples/Ajax.cshtml
@model Person

<button onclick="getPeople()">Get People List</button><br />




<input type="number" id="inputId" name="find" value="">
<button onclick="getPerson('@Url.Action("Details", "Peoples")', 'inputId')">
    Details
</button><br />

<div>
<input type="number" id="input" name="Id" value="">
<button onclick="deletetPerson('@Url.Action("DeletePerson", "Peoples")', 'input')">
    Delete
</button>
</div>

<div id="PeopleList"> <!--Output-->
    
</div>
<div id="PeopleList2">
                          <!--Output-->

</div>

WebAppDB/Views/Peoples/Create.cshtml
@model CreatePersonViewModel

@{ ViewData["Title"] = "person - Create new person"; }

<h1>Wellcome to create new person </h1>

<form asp-action="Create" method="post">
    <label asp-for="FirstName">First name:</label>
    <input asp-for="FirstName" >
    <span asp-validation-for="FirstName"></span>  <br><br>

    <label asp-for="LastName">Last name:</label>
    <input asp-for="LastName" >
    <span asp-validation-for="LastName"></span>  <br><br>

    <label asp-for="CityName">City name:</label>
    <input asp-for="CityName" >
    <span asp-validation-for="CityName"></span>  <br><br>

    <label asp-for="PhoneNumber">Phone no:</label>
    <input asp-for="PhoneNumber" ><br><br>

    <input type="submit" value="Add person">

</form>

WebAppDB/Views/Peoples/Create2.cshtml
@model WebAppDB.Models.Person

@{
    ViewData["Title"] = "Person List";
}


<h1>Create Person</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create2">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for=" FirstName" class="control-label"></label>
                <input asp-for=" FirstName" class="form-control" />
                <span asp-validation-for=" FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="CityName "></label>
                <input asp-for="CityName" list="CountryList" />
                <span asp-validation-for="CityName"></span>
            </div>

            <div class="form-group">
                <datalist id="CountryList">
                    <option value="Malmö">Malmö</option>
                    <option value="Jönköping">Jönköping</option>
                    <option value="Nässjö">Nässjö</option>

                </datalist>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        </div>
    </div>

    <div>
        <a asp-action="Index2">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

WebAppDB/Views/Peoples/Delete2.cshtml
@model WebAppDB.Models.Person
@{
    ViewData["Title"] = "Delete Person";
}
<h1>Delete Person</h1>
<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>
    <form asp-action="Delete2">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index2">Back to List</a>
    </form>
</div>

WebAppDB/Views/Peoples/DeleteOne.cshtml
 @model WebAppDB.Models.Person
@{
    ViewBag.Title = "Delete page";
}
<h1>Wellcome to Delete page</h1>
@ViewBag.Inform

WebAppDB/Views/Peoples/Details2.cshtml
@model WebAppDB.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CityName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CityName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CountryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CountryName)
        </dd>
        <dt class="col-sm-2">
            Person languges
        </dt>
        <dd class="col-sm-10">
            <a asp-action="Index2" asp-controller="Language" asp-route-id="@Model.Id">Languages</a>
           
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit2" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Delete2" asp-route-id="@Model.Id">Delete</a> |
    <a asp-action="Index2">Back to List</a>
</div>

WebAppDB/Views/Peoples/DetailsOne.cshtml
    @model WebAppDB.Models.Person

    @{
    ViewBag.Title = "Home Link";
    }

<h1>Wellcome to Link information page </h1>

<table id="tab">
    <tr>

        <th>Person FName</th>
        <th>Person LName</th>
        <th>City </th>
        <th>Telfon no.</th>
        <th>Person Id</th>
    </tr>

    <tr>
        @if (Model != null)
        {
            <td> @Model.FirstName</td>
        <td> @Model.LastName</td>
        <td> @Model.CityName </td>
        <td> @Model.PhoneNumber </td>
        <td> @Model.Id </td>
        }
    </tr>


</table>

<div>
    <!--
    <a asp-action="DeleteOne" asp-route-id=" put id here" asp-fragment="test">Delete person</a>
    -->
    <form asp-action="DeleteOne">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebAppDB/Views/Peoples/Edit2.cshtml
@model WebAppDB.Models.Person

@{
    ViewData["Title"] = "Edit List";
}


<h1>Edit Person</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit2">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id " />
            <div class="form-group">
                <label asp-for=" FirstName" class="control-label"></label>
                <input asp-for=" FirstName" class="form-control" />
                <span asp-validation-for=" FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CityName "></label>
                <input asp-for="CityName" list="CountryList" />
                <span asp-validation-for="CityName"></span>
            </div>

            <div class="form-group">
                <datalist id="CountryList">
                    <option value="Malmö">Malmö</option>
                    <option value="Jönköping">Jönköping</option>
                    <option value="Nässjö">Nässjö</option>

                </datalist>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index2">Back to List</a>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

WebAppDB/Views/Peoples/Index.cshtml
@model IEnumerable<WebAppDB.Models.Person>
@{
    ViewData["Title"] = "People List";
}


<div class="people">
    <partial name="_ViewPeople" model="@Model" />
</div>

WebAppDB/Views/Peoples/Index2.cshtml
@model IEnumerable<WebAppDB.Models.Person>
   
 @{ ViewData["Title"] = "People List"; }

   <h1>People List</h1>


    <form asp-action="Create2" method="get">

        <input type="submit" value="Add New Person" class="btn btn-danger" />

    </form>
    <table>
        <tr>
            <td>FistName</td>
            <td>LasttName</td>
            <td>PhoneNo.</td>
            <td>City</td>
            <td>Country</td>
            <td>Edit link | Delete link</td>
        </tr>
        @if (Model != null)
        {
        @foreach (Person city in Model)
        {
    <tr>
        <td>@city.FirstName</td>
        <td>@city.LastName</td>
        <td>@city.PhoneNumber</td>
        <td>@city.CityName</td>
       
           <td>@city.CountryName</td>
        
        <td>
            <a asp-action="Edit2" asp-route-id="@city.Id">Edit</a> |
            <a asp-action="Details2" asp-route-id="@city.Id">Details</a> |
            <a asp-action="Delete2" asp-route-id="@city.Id">Delete</a>
        </td>

    </tr>
        }
        }
    </table>
    <div>
        @ViewBag.Msg
    </div>

WebAppDB/Views/Peoples/Message.cshtml
@model List<Person>

    <div class="people">
        <partial name="_ViewMsg" model="@Model" />
    </div>

WebAppDB/Views/Peoples/ViewPeople.cshtml
@model List<Person>



@{
    ViewBag.Title = "Home DataBase";//added by auther
                                    //ViewData["Title"] = "Home Index";
}


<div class="people">
    <partial name="_ViewPeople" model="@Model" />
</div>

WebAppDB/Views/Peoples/ViewPerson.cshtml
@model WebAppDB.Models.Person

@{
    ViewBag.Title = "Home Link";
}

<h1>Wellcome to Link information page </h1>




<div class=" person">
    <partial name="_ViewPerson" model="@Model" />
</div>